### ISSUE TITLE
10.0.5 with a free character

### ISSUE THREAD

**Issue by Nils89** [plusmouse/LibEditMode#3]
Got this error with a fresh chat on the 10.0.5 PTR:

1x ...dOns/GW2_UI/libs/LibEditMode/LibEditModeOverride.lua:220: Usage: C_EditMode.OnLayoutAdded(addedLayoutIndex, activateNewLayout)
[string "=[C]"]: in function `OnLayoutAdded'
[string "@GW2_UI/libs/LibEditMode/LibEditModeOverride.lua"]:220: in function `AddLayout'
[string "@GW2_UI/core/EditMode.lua"]:110: in function `HandleBlizzarEditMode'
[string "@GW2_UI/GW2_ui.lua"]:530: in function <GW2_UI/GW2_ui.lua:520>
[string "@GW2_UI/GW2_ui.lua"]:835: in function <GW2_UI/GW2_ui.lua:833>

Locals:
(*temporary) = 3

**Comment by Nils89** [comment]
Comment: Happens on every character

**Comment by Nils89** [comment]
ATM on 10.0.5 it is not possible to add new layouts and if there is no layout which can be edited it won't work and errors

**Comment by Nils89** [comment]
seams like the API has now a 2nd argument:

`function EditModeManagerFrameMixin:MakeNewLayout(newLayoutInfo, layoutType, layoutName)
	if newLayoutInfo and layoutName and layoutName ~= "" then
		newLayoutInfo.layoutType = layoutType;
		newLayoutInfo.layoutName = layoutName;

		local newLayoutIndex;
		if self.highestLayoutIndexByType[layoutType] then
			newLayoutIndex = self.highestLayoutIndexByType[layoutType] + 1;
		elseif (layoutType == Enum.EditModeLayoutType.Character) and self.highestLayoutIndexByType[Enum.EditModeLayoutType.Account] then
			newLayoutIndex = self.highestLayoutIndexByType[Enum.EditModeLayoutType.Account] + 1;
		else
			newLayoutIndex = Enum.EditModePresetLayoutsMeta.NumValues + 1;
		end

		local activateNewLayout = not EditModeUnsavedChangesDialog:HasPendingSelectedLayout();

		table.insert(self.layoutInfo.layouts, newLayoutIndex, newLayoutInfo);
		self:SaveLayouts();
		C_EditMode.OnLayoutAdded(newLayoutIndex, activateNewLayout);
	end
end`

But also with that one set to true, I got this error messages and no new layout is created:

[string "@GW2_UI/libs/LibEditMode/LibEditModeOverride.lua"]:196: in function `ApplyChanges'


Comment out "ShowUIPanel(EditModeManagerFrame)
  HideUIPanel(EditModeManagerFrame)" at the ApplyChanges function removes the error, but no new Layout

**Comment by Nils89** [comment]
I got this fixed by adding a timer of 1 sec to the ApplyChanges function:

```lua
function lib:ApplyChanges()
  assert(not InCombatLockdown(), "Cannot move frames in combat")
  lib:SaveOnly()

  if not issecurevariable(DropDownList1, "numButtons") then
    ShowUIPanel(AddonList)
    HideUIPanel(AddonList)
  end

  C_Timer.After(1, function()
    ShowUIPanel(EditModeManagerFrame)
    HideUIPanel(EditModeManagerFrame)
  end)
end
```
And to get the new create Layout active I need to Apply the Changes, set the creates layout as active and apply the changes again:

```lua
    LEMO:LoadLayouts()
    LEMO:AddLayout(Enum.EditModeLayoutType.Account, "GW2_Layout")
    LEMO:SetActiveLayout("GW2_Layout")
    LEMO:ApplyChanges()
    LEMO:SetActiveLayout("GW2_Layout")
    LEMO:ApplyChanges()
```

**Comment by plusmouse** [comment]
I've put a fix in the latest commit. Basically I set the code to only do the active layout API call after you have called `SaveOnly` or `ApplyChanges` - that gets it to apply correctly.
