### ISSUE TITLE
Wrong version on CurseForge

### ISSUE THREAD

**Issue by Goldpaw** [plusmouse/LibEditMode#6]
When downloading the 1.0.10 version from CurseForge, either through the client or manually, the zip does contain a toc file with 1.0.10  as its version, but the library version included is still 1.0.9, which lacks the IsReady()  method and so on. 

Causes a few bugs when not embedding it.

**Comment by plusmouse** [comment]
I've made a new release 1.0.11 which will be available from Curseforge shortly
